# Generated by Django 6.0 on 2026-02-22 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_categorybudget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='categorybudget',
            index=models.Index(fields=['user', 'year', 'month'], name='expenses_ca_user_id_0141d5_idx'),
        ),
        migrations.AddIndex(
            model_name='categorybudget',
            index=models.Index(fields=['category', 'year', 'month'], name='expenses_ca_categor_c000cb_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'category', 'expense_date'], name='expenses_ex_user_id_9db599_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'is_deleted', 'expense_date'], name='expenses_ex_user_id_9e2a70_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_date', 'category'], name='expenses_ex_expense_b82ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlybudget',
            index=models.Index(fields=['user', 'year', 'month'], name='expenses_mo_user_id_f2bd3a_idx'),
        ),
    ]
