# Generated by Django 6.0 on 2026-02-22 13:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('forecast', 'Spending Forecast'), ('anomaly', 'Unusual Spending'), ('trend', 'Spending Trend'), ('suggestion', 'Saving Suggestion'), ('risk', 'Budget Risk')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('danger', 'Critical')], default='info', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('applies_to_month', models.IntegerField(blank=True, null=True)),
                ('applies_to_year', models.IntegerField(blank=True, null=True)),
                ('predicted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_engine_s_user_id_47d681_idx'), models.Index(fields=['user', 'insight_type'], name='ai_engine_s_user_id_5a55cb_idx')],
            },
        ),
    ]
